import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {signInWithEmailAndPassword, signOut, onAuthStateChanged} from 'firebase/auth';
import {collection, doc, onSnapshot, setDoc, addDoc, updateDoc, deleteDoc, serverTimestamp, query, orderBy} from 'firebase/firestore';
import {auth, db} from './firebase.js';
import './style.css';

const roles = {
  'admin@taqwa.com': {name:'Dr. Shakil', role:'owner', label:'OWNER ADMIN'},
  'nusrat@taqwa.com': {name:'Dr. Nusrat', role:'viewAdmin', label:'VIEW ADMIN'},
  'suraiya@taqwa.com': {name:'Suraiya Technologist', role:'lab', label:'STAFF + LAB'},
  'shawon@taqwa.com': {name:'Shawon', role:'reception', label:'RECEPTION'},
  'golapi@taqwa.com': {name:'Golapi', role:'staff', label:'STAFF'}
};
const staffList = [
  {id:'golapi', name:'Golapi', salary:6000, leave:0, inStart:'09:00', inEnd:'09:15', lateEnd:'09:30', outStart:'19:30', outEnd:'19:45'},
  {id:'suraiya', name:'Suraiya Technologist', salary:18000, leave:2, inStart:'09:00', inEnd:'09:15', lateEnd:'09:30', outStart:'20:00', outEnd:'22:00'},
  {id:'shawon', name:'Shawon', salary:9000, leave:0, inStart:'09:00', inEnd:'09:15', lateEnd:'09:30', outStart:'20:00', outEnd:'22:00', fridayOutStart:'16:00'}
];
const initialTests = ['RBS','Creatinine','Hb%','Uric Acid','Lipid Profile','Sugar/Fasting','SGPT','SGOT','Blood Group','Bilirubin','Widal','Weil Felix','CRP','RA','ASO','HBsAg','HIV','HCV','T3','T4','TSH','Prolactin','HbA1c','NS1','IgG/IgM','H. Pylori','VDRL','FT3','FT4','CBC Manual','CBC Cell Counter','Urine R/E','Stool R/E'];
function pad(n){return String(n).padStart(2,'0')}function today(){const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}function ymNow(){return today().slice(0,7)}function timeNow(){const d=new Date();return `${pad(d.getHours())}:${pad(d.getMinutes())}`}function min(t){const [h,m]=String(t||'00:00').split(':').map(Number);return h*60+m}function between(n,s,e){return min(n)>=min(s)&&min(n)<=min(e)}function fmtTime(iso){if(!iso)return '-';return new Date(iso).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:true})}function fmtDate(iso){if(!iso)return '-';return new Date(iso).toLocaleDateString('en-GB')}function monthName(ym){const [y,m]=ym.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-US',{month:'long',year:'numeric'})}function daysInMonth(ym){const [y,m]=ym.split('-').map(Number);return new Date(y,m,0).getDate()}function isFriday(ds){return new Date(ds+'T12:00:00').getDay()===5}function coll(name){return collection(db,name)}function roleFor(email){return roles[email]||{name:email,role:'staff',label:'STAFF'}}function canEdit(profile){return profile.role==='owner'}function canViewAll(profile){return ['owner','viewAdmin'].includes(profile.role)}function canLab(profile){return ['owner','viewAdmin','lab'].includes(profile.role)}function canReception(profile){return ['owner','viewAdmin','reception'].includes(profile.role)}function canDoLab(profile){return profile.role==='owner'||profile.role==='lab'}function canDoReception(profile){return profile.role==='owner'||profile.role==='reception'}

function App(){const [user,setUser]=useState(null);const [profile,setProfile]=useState(null);useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setProfile(u?roleFor(u.email):null)}),[]);return <><header><h1>TAQWA Diagnostic Center Manager</h1><div>React + Firebase Cloud Version</div></header>{!user?<Login/>:<Dashboard user={user} profile={profile}/>}</>}
function Login(){const [email,setEmail]=useState('admin@taqwa.com'),[pass,setPass]=useState(''),[err,setErr]=useState('');async function login(e){e.preventDefault();setErr('');try{await signInWithEmailAndPassword(auth,email,pass)}catch(ex){setErr('Login failed: '+ex.message)}}return <div className="container"><div className="card login"><h2>Login</h2><form onSubmit={login}><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@taqwa.com"/><label>Password</label><input value={pass} onChange={e=>setPass(e.target.value)} type="password" placeholder="Password"/><br/><br/><button>Login</button></form>{err&&<p className="notice">{err}</p>}<p className="muted">Firebase Authentication দিয়ে Login হবে।</p></div></div>}
function useCollection(name){const [data,setData]=useState([]);useEffect(()=>{const q=query(coll(name));return onSnapshot(q,s=>setData(s.docs.map(d=>({id:d.id,...d.data()}))))},[name]);return data}
function Dashboard({user,profile}){const [tab,setTab]=useState('dash');const tests=useCollection('labTests');const entries=useCollection('labEntries');const att=useCollection('attendance');const patients=useCollection('patients');useEffect(()=>{seedTests()},[]);async function seedTests(){const seedKey=localStorage.getItem('seededTestsCloudV1'); if(seedKey)return; for(const name of initialTests){await setDoc(doc(db,'labTests',name.replaceAll('/','_').replaceAll(' ','_')), {name, stockMl:0, mlPerTest:0, openingStock:0, createdAt:serverTimestamp()}, {merge:true});} localStorage.setItem('seededTestsCloudV1','1')}
const nav=[['dash','Dashboard'],['att','Attendance']]; if(canLab(profile))nav.push(['lab','Lab Stock']); if(canReception(profile))nav.push(['outdoor','Outdoor Visit']); if(canViewAll(profile))nav.push(['salary','Salary']); if(canViewAll(profile))nav.push(['admin','Admin Panel']);
return <div className="container"><div className="card top"><div><h2 style={{margin:'0'}}>{profile.name}</h2><span className="pill">{profile.label}</span><div className="muted">{user.email}</div></div><button className="secondary" style={{maxWidth:150}} onClick={()=>signOut(auth)}>Logout</button></div><div className="nav">{nav.map(([k,v])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{v}</button>)}</div>{tab==='dash'&&<Summary tests={tests} entries={entries} att={att} patients={patients}/>} {tab==='att'&&<Attendance profile={profile} att={att}/>} {tab==='lab'&&<Lab profile={profile} tests={tests} entries={entries}/>} {tab==='outdoor'&&<Outdoor profile={profile} patients={patients}/>} {tab==='salary'&&<Salary att={att}/>} {tab==='admin'&&<Admin profile={profile}/>}</div>}
function Summary({tests,entries,att,patients}){const [q,setQ]=useState('');const [ym,setYm]=useState(ymNow());const monthEntries=entries.filter(e=>e.date?.startsWith(ym));const todayAtt=att.filter(a=>a.date===today());const totalCount=monthEntries.reduce((s,e)=>s+(+e.count||0),0);const totalUsed=tests.reduce((s,t)=>s+usedByMonth(t,entries,ym),0);const low=tests.filter(t=>stockPercent(t,entries)<10 && (+t.openingStock||+t.stockMl||0)>0).length;const list=tests.filter(t=>t.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));return <div className="card"><h2>📊 Dashboard Summary</h2><div className="miniStats"><div className="mini"><b>{String(totalCount).padStart(2,'0')}</b><div>Total Test</div></div><div className="mini"><b>{patients.filter(p=>p.date===today()).length}</b><div>Outdoor</div></div><div className="mini"><b>{todayAtt.filter(a=>a.inTime).length}</b><div>Attendance</div></div><div className="mini"><b>{low}</b><div>Low Stock</div></div><div className="mini"><b>{totalUsed.toFixed(1)}</b><div>Used ml</div></div></div><div className="grid g2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="টেস্ট সার্চ"/><input type="month" value={ym} onChange={e=>setYm(e.target.value)}/></div><p className="muted">এই Summary এক স্ক্রিনে ফিট করার জন্য Compact করা হয়েছে। মাসে কত টেস্ট হয়েছে, কত ml used হয়েছে, remaining stock—সব এখানেই দেখা যাবে।</p><div className="tablewrap"><table className="compact"><thead><tr><th>Test</th><th>Stock / ml</th><th>মাসে / Used</th><th>Remain / যাবে</th><th>Status</th></tr></thead><tbody>{list.map(t=>{const r=remaining(t,entries);const p=stockPercent(t,entries);const monthCount=countByMonth(t,entries,ym);const monthUsed=usedByMonth(t,entries,ym);const possible=(+t.mlPerTest||0)>0?Math.floor(r/(+t.mlPerTest||1)):0;const notSet=(+t.stockMl||0)===0||(+t.mlPerTest||0)===0;return <tr key={t.id} className={p<10 && (+t.openingStock||+t.stockMl||0)>0?'blinkLow':''}><td><b>{t.name}</b><div className="muted">Admin only</div></td><td><b>{+t.stockMl||0}</b><div className="muted">ml/Test: {+t.mlPerTest||0}</div></td><td><b>{monthCount}</b><div className="muted">Used ml: {monthUsed.toFixed(2)}</div></td><td><b>{r.toFixed(2)}</b><div className="muted">আর যাবে: {possible}</div></td><td>{notSet?<span className="pill warn">Manual Set</span>:p<10?<span className="pill warn">Below 10%</span>:<span className="pill ok">OK</span>}</td></tr>})}</tbody></table></div></div>}
function Attendance({profile,att}){const selfId = profile.role==='lab'?'suraiya':profile.role==='reception'?'shawon':profile.role==='staff'?'golapi':'admin'; if(canViewAll(profile))return <AttendanceAdmin att={att}/>; return <StaffAttendance staffId={selfId}/>}
function outStart(s,ds=today()){return s.fridayOutStart&&isFriday(ds)?s.fridayOutStart:s.outStart}function stateFor(s){const n=timeNow(); if(between(n,s.inStart,s.inEnd))return 'in'; if(between(n,outStart(s),s.outEnd))return 'out'; return 'closed'}
function StaffAttendance({staffId}){const s=staffList.find(x=>x.id===staffId)||staffList[0];const [rec,setRec]=useState(null);useEffect(()=>onSnapshot(doc(db,'attendance',`${today()}_${staffId}`),d=>setRec(d.exists()?d.data():{})),[staffId]);const video=useRef(null),stream=useRef(null);const [mode,setMode]=useState('');async function openCam(m){setMode(m);stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});video.current.srcObject=stream.current}async function savePhoto(){const canvas=document.createElement('canvas');canvas.width=video.current.videoWidth;canvas.height=video.current.videoHeight;canvas.getContext('2d').drawImage(video.current,0,0);const photo=canvas.toDataURL('image/jpeg',0.7);const data={staffId,staffName:s.name,date:today(),updatedAt:serverTimestamp()};if(mode==='in'){data.inTime=new Date().toISOString();data.inPhoto=photo}else{data.outTime=new Date().toISOString();data.outPhoto=photo}await setDoc(doc(db,'attendance',`${today()}_${staffId}`),data,{merge:true});stream.current?.getTracks().forEach(t=>t.stop());setMode('')}
const st=stateFor(s);return <div className="card"><h2>আজকের হাজিরা</h2><div className="notice">এখন সময় {new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:true})}. Check-in: {to12(s.inStart)}–{to12(s.inEnd)} | Check-out: {to12(outStart(s))}–{to12(s.outEnd)}</div><div className="grid g2"><div className="card"><h3>আসার সময় / Check-in</h3><p>📷 Live Camera Required<br/>Gallery Upload Not Allowed<br/><b>Reception Clock Must Be Visible</b></p><button disabled={!!rec?.inTime||st!=='in'} onClick={()=>openCam('in')}>📷 Take Photo Check-In</button></div><div className="card"><h3>যাওয়ার সময় / Check-out</h3><p>সময়: {to12(outStart(s))} থেকে {to12(s.outEnd)}</p><button disabled={!!rec?.outTime||st!=='out'} onClick={()=>openCam('out')}>📷 Take Photo Check-Out</button></div></div>{mode&&<div className="card"><video ref={video} autoPlay playsInline/><br/><button onClick={savePhoto}>📷 Take Photo & Save</button></div>}<p className="statusline">Check-in: {fmtTime(rec?.inTime)} | Check-out: {fmtTime(rec?.outTime)}</p></div>}
function to12(t){const [h,m]=t.split(':').map(Number);return new Date(2020,0,1,h,m).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:true})}
function AttendanceAdmin({att}){const ym=ymNow();return <div className="card"><h2>Attendance Records</h2><div className="tablewrap"><table><thead><tr><th>Date</th><th>Staff</th><th>In</th><th>Out</th><th>Status</th><th>Photo</th></tr></thead><tbody>{att.filter(a=>a.date?.startsWith(ym)).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(a=><tr key={a.id}><td>{a.date}</td><td>{a.staffName}</td><td>{fmtTime(a.inTime)}</td><td>{fmtTime(a.outTime)}</td><td>{a.inTime&&a.outTime?<span className="pill ok">Present</span>:a.inTime?<span className="pill warn">Incomplete</span>:<span className="pill bad">Absent</span>}</td><td>{a.inPhoto&&<img src={a.inPhoto} className="photo"/>}</td></tr>)}</tbody></table></div></div>}
function stockPercent(t,entries){const opening=+t.openingStock||+t.stockMl||0;if(!opening)return 100;return remaining(t,entries)/opening*100}function used(t,entries){return entries.filter(e=>e.testId===t.id).reduce((s,e)=>s+(+e.count||0)*(+t.mlPerTest||0),0)}function countByMonth(t,entries,ym){return entries.filter(e=>e.testId===t.id&&e.date?.startsWith(ym)).reduce((s,e)=>s+(+e.count||0),0)}function usedByMonth(t,entries,ym){return countByMonth(t,entries,ym)*(+t.mlPerTest||0)}function remaining(t,entries){return Math.max(0,(+t.stockMl||0)-used(t,entries))}
function Lab({profile,tests,entries}){const [sub,setSub]=useState('summary');return <div className="card"><h2>Lab Stock</h2><div className="tabBtns"><button className={sub==='summary'?'active':''} onClick={()=>setSub('summary')}>Summary</button><button onClick={()=>setSub('setup')}>Stock Setup</button><button onClick={()=>setSub('entry')}>Test Entry</button><button onClick={()=>setSub('daily')}>Date-wise Entry</button></div>{sub==='summary'&&<LabSummary tests={tests} entries={entries}/>} {sub==='setup'&&<StockSetup profile={profile} tests={tests}/>} {sub==='entry'&&<TestEntry profile={profile} tests={tests}/>} {sub==='daily'&&<DailyEntry profile={profile} tests={tests} entries={entries}/>}</div>}
function LabSummary({tests,entries}){const [q,setQ]=useState('');const [ym,setYm]=useState(ymNow());const list=tests.filter(t=>t.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));return <div><div className="grid g2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="টেস্ট সার্চ"/><input type="month" value={ym} onChange={e=>setYm(e.target.value)}/></div><br/><div className="tablewrap"><table className="compact"><thead><tr><th>Test</th><th>Stock / ml</th><th>মাসে / Used</th><th>Remaining</th><th>Status</th></tr></thead><tbody>{list.map(t=>{const p=stockPercent(t,entries);const monthCount=countByMonth(t,entries,ym);const monthUsed=usedByMonth(t,entries,ym);const notSet=(+t.stockMl||0)===0||(+t.mlPerTest||0)===0;return <tr key={t.id} className={p<10 && (+t.openingStock||+t.stockMl||0)>0?'blinkLow':''}><td><b>{t.name}</b><div className="muted">Admin only</div></td><td><b>{+t.stockMl||0}</b><div className="muted">ml/Test: {+t.mlPerTest||0}</div></td><td><b>{monthCount}</b><div className="muted">Used ml: {monthUsed.toFixed(2)}</div></td><td>{remaining(t,entries).toFixed(2)}</td><td>{notSet?<span className="pill warn">Manual Set</span>:p<10?<span className="pill warn">Below 10%</span>:<span className="pill ok">OK</span>}</td></tr>})}</tbody></table></div></div>}
function StockSetup({profile,tests}){const [q,setQ]=useState(''),[selected,setSelected]=useState(''),[stock,setStock]=useState(''),[ml,setMl]=useState('');const found=tests.find(t=>t.id===selected);useEffect(()=>{if(found){setStock(found.stockMl||0);setMl(found.mlPerTest||0)}},[selected]);async function save(){if(!canDoLab(profile))return;await updateDoc(doc(db,'labTests',selected),{stockMl:+stock||0, openingStock:+stock||0, mlPerTest:+ml||0, updatedAt:serverTimestamp()})}const list=tests.filter(t=>t.name.toLowerCase().includes(q.toLowerCase()));return <div className="grid g2"><div><label>Search Test</label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="RBS লিখুন"/><label>Select Test</label><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select</option>{list.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div><label>Stock ml</label><input value={stock} onChange={e=>setStock(e.target.value)} type="number"/><label>ml/Test</label><input value={ml} onChange={e=>setMl(e.target.value)} type="number" step="0.001"/><button disabled={!selected||!canDoLab(profile)} onClick={save}>Save Stock</button>{!canDoLab(profile)&&<p className="notice">View only</p>}</div></div>}
function TestEntry({profile,tests}){const [testId,setTestId]=useState(''),[date,setDate]=useState(today()),[count,setCount]=useState('');async function save(){if(!canDoLab(profile))return;const t=tests.find(x=>x.id===testId);await addDoc(coll('labEntries'),{testId,testName:t?.name,date,count:+count||0,by:auth.currentUser.email,createdAt:serverTimestamp()});setCount('')}return <div className="grid g3"><div><label>Test</label><select value={testId} onChange={e=>setTestId(e.target.value)}><option>Select</option>{tests.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div><label>Date</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div><label>Count</label><input type="number" value={count} onChange={e=>setCount(e.target.value)}/><button disabled={!testId||!canDoLab(profile)} onClick={save}>Save Entry</button></div></div>}
function DailyEntry({profile,tests,entries}){const [q,setQ]=useState(''),[ym,setYm]=useState(ymNow());const list=tests.filter(t=>t.name.toLowerCase().includes(q.toLowerCase()));async function setDay(t,ds,val){if(!canDoLab(profile))return;await addDoc(coll('labEntries'),{testId:t.id,testName:t.name,date:ds,count:+val||0,by:auth.currentUser.email,createdAt:serverTimestamp()})}return <div><label>Search Test</label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="টেস্টের নাম লিখুন"/><label>Month</label><input type="month" value={ym} onChange={e=>setYm(e.target.value)}/><h3>{monthName(ym)}</h3>{list.map(t=><div className="card" key={t.id}><b>{t.name}</b><div className="grid g4">{Array.from({length:daysInMonth(ym)},(_,i)=>{const ds=`${ym}-${pad(i+1)}`;const total=entries.filter(e=>e.testId===t.id&&e.date===ds).reduce((s,e)=>s+(+e.count||0),0);return <div key={ds}><label>{i+1} তারিখ ({total})</label><input disabled={!canDoLab(profile)} type="number" placeholder="0" onBlur={e=>{if(e.target.value)setDay(t,ds,e.target.value)}}/></div>})}</div></div>)}</div>}
function Outdoor({profile,patients}){const [form,setForm]=useState({date:today(),name:'',mobile:'',address:'',fee:'',diagnosis:'',followup:'',procedure:'',notes:''});async function save(){if(!canDoReception(profile))return;await addDoc(coll('patients'),{...form,fee:+form.fee||0,by:auth.currentUser.email,createdAt:serverTimestamp()});setForm({...form,name:'',mobile:'',address:'',fee:'',diagnosis:'',followup:'',procedure:'',notes:''})}return <div className="card"><h2>Outdoor Visit / Reception Entry</h2><div className="grid g2"><Input f="date" type="date" form={form} setForm={setForm}/><Input f="name" label="Patient Name" form={form} setForm={setForm}/><Input f="mobile" label="Mobile" form={form} setForm={setForm}/><Input f="address" label="Address" form={form} setForm={setForm}/><Input f="fee" label="Visit Fee" type="number" form={form} setForm={setForm}/><Input f="diagnosis" label="Diagnosis" form={form} setForm={setForm}/><Input f="followup" label="Follow-up Date" type="date" form={form} setForm={setForm}/><Input f="procedure" label="Procedure" form={form} setForm={setForm}/></div><label>Notes</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button disabled={!canDoReception(profile)} onClick={save}>Save Patient Entry</button><h3>Recent Patients</h3><div className="tablewrap"><table><thead><tr><th>Date</th><th>Name</th><th>Mobile</th><th>Fee</th><th>Diagnosis</th><th>Follow-up</th></tr></thead><tbody>{patients.sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(p=><tr key={p.id}><td>{p.date}</td><td>{p.name}</td><td>{p.mobile}</td><td>{p.fee}</td><td>{p.diagnosis}</td><td>{p.followup}</td></tr>)}</tbody></table></div></div>}
function Input({f,label,type='text',form,setForm}){return <div><label>{label||f}</label><input type={type} value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}/></div>}
function Salary({att}){const ym=ymNow(),days=daysInMonth(ym);return <div className="card"><h2>Monthly Salary Calculation</h2><h3>{monthName(ym)}</h3><div className="tablewrap"><table><thead><tr><th>Staff</th><th>Monthly Salary</th><th>Present</th><th>Paid Leave</th><th>Absent Cut</th><th>Payable</th></tr></thead><tbody>{staffList.map(s=>{let present=att.filter(a=>a.staffId===s.id&&a.date?.startsWith(ym)&&a.inTime&&a.outTime).length;let absent=Math.max(0,days-present);let paidLeave=Math.min(s.leave,absent);let cut=Math.max(0,absent-paidLeave);let payable=Math.round((s.salary/days)*(days-cut));return <tr key={s.id}><td>{s.name}<div className="muted">{s.leave?`মাসে ${s.leave} দিন paid leave`:''}{s.fridayOutStart?' শুক্রবার 04:00 PM checkout allowed':''}</div></td><td>{s.salary} টাকা</td><td>{present}</td><td>{paidLeave}</td><td>{cut}</td><td><b>{payable} টাকা</b></td></tr>})}</tbody></table></div><p className="footerNote">Suraiya salary 18,000 টাকা; মাসে ২ দিন ছুটি থাকবে; ২ দিনের বেশি absent হলে salary cut হবে।</p></div>}
function Admin({profile}){return <div className="card"><h2>Admin Panel</h2>{profile.role==='viewAdmin'&&<p className="notice">Dr. Nusrat View Admin: সব দেখতে পারবেন, কিন্তু কোনো পরিবর্তন করতে পারবেন না।</p>}<div className="tablewrap"><table><thead><tr><th>Email</th><th>Name</th><th>Role</th><th>Permission</th></tr></thead><tbody>{Object.entries(roles).map(([email,r])=><tr key={email}><td>{email}</td><td>{r.name}</td><td>{r.label}</td><td>{r.role==='owner'?'Edit/View All':r.role==='viewAdmin'?'View All Only':r.role==='lab'?'Lab + Attendance':r.role==='reception'?'Outdoor + Attendance':'Attendance Only'}</td></tr>)}</tbody></table></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
